.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. trustcoin_qt test_trustcoin_qt
clean: FORCE
	$(MAKE) -C .. trustcoin_qt_clean test_trustcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_trustcoin_qt_check
trustcoin-qt trustcoin-qt.exe: FORCE
	 $(MAKE) -C .. trustcoin_qt
